server:
  port: 8635

simbot:
  core:
    # bot qq账号和密码
    bots: 1943048206:Qweasd12345

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/robot?useUnicode=true&characterEncoding=utf8&useSSL=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: robot
    password: Woshiwudi1101.
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.cgh.ro635bot.entity

# 高德 API KEY
weather:
  key:

# 天行数据 API KEY
tian:
  key:

# 日志
logging:
  level:
    com.cgh.ro635bot.listener.qqgroup: DEBUG